name: "Shinobi Pro"
version: "1.0.1"
slug: "shinobi"
description: "Shinobi CCTV/NVR with a local MariaDB database in the same add-on container"
url: "https://github.com/Kyguyog/addon-shinobi-updated"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ports:
  8080/tcp: 7440
ports_description:
  8080/tcp: "Shinobi web interface"
webui: "http://[HOST]:[PORT:8080]"
options:
  log_level: info
  super_username: admin@shinobi.video
  super_password: admin
  mysql_username: shinobi
  mysql_password: sh1n0b1
  mysql_database: shinobi
  mysql_root_password: rootpassword
  shinobi_update: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  super_username: str
  super_password: password
  mysql_username: str
  mysql_password: password
  mysql_database: str
  mysql_root_password: password
  shinobi_update: bool
